# Generated by Django 4.1.2 on 2022-10-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_alter_place4_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='place4',
        ),
    ]
